---
- Aston Martin:
    Year Founded: 1913
    Website: www.astonmartin.com
    Founded By:
        - Lionel Martin
        - Robert Bamford
- Fiat:
    Year Founded: 1899
    Website: www.fiat.com
    Founded By:
        - Giovanni Agnelli
- Volkswagen:
    Year Founded: 1937
    Website: www.vw.com
    Founded By:
        - German Labour Front
- Vauxhall:
    Year Founded: 1857
    Website: www.vauxhall.co.uk
    Founded By:
        - Alexander Wilson
- Peugeot:
    Year Founded: 1810
    Website: www.peugeot.com
    Founded By:
        - Jean-Pierre Peugeot
- Renault:
    Year Founded: 1899
    Website: www.renault.com
    Founded By:
        - Louis Renault
        - Marcel Renault
        - Fernand Renault
...