- name: Variables
  hosts: centos1
  gather_facts: false
  vars_prompt: # <- Prompts the user to input credentials.
    - name: password
      prompt: What is your password?
      private: true

  vars_files:
    - Variables.yaml

  vars:
    example_key: example_value
    dict:
      dict_key: This is a dictionary value
    inline_dict:
      {inline_dict_key: This is an inline dict value}
    named_list:
      - item 1
      - item 2
      - item 3
      - item 4
    inline_named_list: [item1, item2, item3, item4]

  tasks:
    - name: Host Vars
      ansible.builtin.debug:
        msg: "Host Vars Ansible Port {{ hostvars[ansible_hostname].ansible_portee | default('22') }}"
    - name: Example Key Test
      ansible.builtin.debug:
        msg: "Example Key: {{ example_key }}"
    - name: Example Username
      ansible.builtin.debug:
        msg: "Username: {{ username }}"
    - name: External Dict
      ansible.builtin.debug:
        msg: "External Dict: {{ external_dict }}"
    - name: Named List
      ansible.builtin.debug:
        msg: |
         "Named List: {{ named_list }}"
         "Named List Item 1 : {{ named_list.0 }}"
         "Named List Item 1 Alt : {{ named_list[0] }}"
    - name: Inline Named List
      ansible.builtin.debug:
        msg: |
         "Named List: {{ inline_named_list }}"
         "Named List Item 1 : {{ inline_named_list.0 }}"
         "Named List Item 1 Alt : {{ inline_named_list[0] }}"
    - name: Dict Key Test
      ansible.builtin.debug:
        msg: |
          "Dict: {{ dict }},
           Dict Key: {{ dict.dict_key }}, Dict Key Alt {{ dict['dict_key'] }}"
    - name: Inline Dict Key Test
      ansible.builtin.debug:
        msg: |
          "Inline Dict: {{ inline_dict }},
           Dict Key: {{ inline_dict.inline_dict_key }}, Dict Key Alt {{ inline_dict['inline_dict_key'] }}"
...
